# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 72629262f07932304ea44e77de18715b6b70a903fab215424ddbc499ddbebd58fbccdd3b9c799dfb2f687f8c1818021b8f301c93f66dd30a1bf6d71bbd82ce35

test:
  secret_key_base: 55ba55e1ccb475f4ce31cfd461e77de602f4d44fbdc6171d247a3748de2aa2403031d84e06425c69c4af8c035bcf04530c5559d1c52761a4131605ae0a369c4d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
